export type Country = { value: string; label: string };

// CEDEAO / ECOWAS — remontés en tête de liste
export const CEDEAO_COUNTRIES: Country[] = [
  { value: "CI", label: "🇨🇮 Côte d'Ivoire" },
  { value: "SN", label: "🇸🇳 Sénégal" },
  { value: "ML", label: "🇲🇱 Mali" },
  { value: "BF", label: "🇧🇫 Burkina Faso" },
  { value: "BJ", label: "🇧🇯 Bénin" },
  { value: "TG", label: "🇹🇬 Togo" },
  { value: "NE", label: "🇳🇪 Niger" },
  { value: "GN", label: "🇬🇳 Guinée" },
  { value: "GW", label: "🇬🇼 Guinée-Bissau" },
  { value: "NG", label: "🇳🇬 Nigeria" },
  { value: "GH", label: "🇬🇭 Ghana" },
  { value: "LR", label: "🇱🇷 Libéria" },
  { value: "SL", label: "🇸🇱 Sierra Leone" },
  { value: "CV", label: "🇨🇻 Cap-Vert" },
  { value: "GM", label: "🇬🇲 Gambie" },
  { value: "MR", label: "🇲🇷 Mauritanie" },
];

// Tous les autres pays — ordre alphabétique français
export const OTHER_COUNTRIES: Country[] = [
  { value: "AF", label: "🇦🇫 Afghanistan" },
  { value: "ZA", label: "🇿🇦 Afrique du Sud" },
  { value: "AL", label: "🇦🇱 Albanie" },
  { value: "DZ", label: "🇩🇿 Algérie" },
  { value: "DE", label: "🇩🇪 Allemagne" },
  { value: "AD", label: "🇦🇩 Andorre" },
  { value: "AO", label: "🇦🇴 Angola" },
  { value: "AG", label: "🇦🇬 Antigua-et-Barbuda" },
  { value: "SA", label: "🇸🇦 Arabie saoudite" },
  { value: "AR", label: "🇦🇷 Argentine" },
  { value: "AM", label: "🇦🇲 Arménie" },
  { value: "AU", label: "🇦🇺 Australie" },
  { value: "AT", label: "🇦🇹 Autriche" },
  { value: "AZ", label: "🇦🇿 Azerbaïdjan" },
  { value: "BS", label: "🇧🇸 Bahamas" },
  { value: "BH", label: "🇧🇭 Bahreïn" },
  { value: "BD", label: "🇧🇩 Bangladesh" },
  { value: "BB", label: "🇧🇧 Barbade" },
  { value: "BE", label: "🇧🇪 Belgique" },
  { value: "BZ", label: "🇧🇿 Belize" },
  { value: "BT", label: "🇧🇹 Bhoutan" },
  { value: "BY", label: "🇧🇾 Biélorussie" },
  { value: "BO", label: "🇧🇴 Bolivie" },
  { value: "BA", label: "🇧🇦 Bosnie-Herzégovine" },
  { value: "BW", label: "🇧🇼 Botswana" },
  { value: "BR", label: "🇧🇷 Brésil" },
  { value: "BN", label: "🇧🇳 Brunéi" },
  { value: "BG", label: "🇧🇬 Bulgarie" },
  { value: "BI", label: "🇧🇮 Burundi" },
  { value: "KH", label: "🇰🇭 Cambodge" },
  { value: "CM", label: "🇨🇲 Cameroun" },
  { value: "CA", label: "🇨🇦 Canada" },
  { value: "CF", label: "🇨🇫 Centrafrique" },
  { value: "CL", label: "🇨🇱 Chili" },
  { value: "CN", label: "🇨🇳 Chine" },
  { value: "CY", label: "🇨🇾 Chypre" },
  { value: "CO", label: "🇨🇴 Colombie" },
  { value: "KM", label: "🇰🇲 Comores" },
  { value: "CG", label: "🇨🇬 Congo" },
  { value: "CD", label: "🇨🇩 Congo (RDC)" },
  { value: "KP", label: "🇰🇵 Corée du Nord" },
  { value: "KR", label: "🇰🇷 Corée du Sud" },
  { value: "CR", label: "🇨🇷 Costa Rica" },
  { value: "HR", label: "🇭🇷 Croatie" },
  { value: "CU", label: "🇨🇺 Cuba" },
  { value: "DK", label: "🇩🇰 Danemark" },
  { value: "DJ", label: "🇩🇯 Djibouti" },
  { value: "DM", label: "🇩🇲 Dominique" },
  { value: "EG", label: "🇪🇬 Égypte" },
  { value: "AE", label: "🇦🇪 Émirats arabes unis" },
  { value: "EC", label: "🇪🇨 Équateur" },
  { value: "ER", label: "🇪🇷 Érythrée" },
  { value: "ES", label: "🇪🇸 Espagne" },
  { value: "EE", label: "🇪🇪 Estonie" },
  { value: "SZ", label: "🇸🇿 Eswatini" },
  { value: "US", label: "🇺🇸 États-Unis" },
  { value: "ET", label: "🇪🇹 Éthiopie" },
  { value: "FJ", label: "🇫🇯 Fidji" },
  { value: "FI", label: "🇫🇮 Finlande" },
  { value: "FR", label: "🇫🇷 France" },
  { value: "GA", label: "🇬🇦 Gabon" },
  { value: "GE", label: "🇬🇪 Géorgie" },
  { value: "GD", label: "🇬🇩 Grenade" },
  { value: "GT", label: "🇬🇹 Guatemala" },
  { value: "GQ", label: "🇬🇶 Guinée équatoriale" },
  { value: "GY", label: "🇬🇾 Guyana" },
  { value: "HT", label: "🇭🇹 Haïti" },
  { value: "HN", label: "🇭🇳 Honduras" },
  { value: "HU", label: "🇭🇺 Hongrie" },
  { value: "IN", label: "🇮🇳 Inde" },
  { value: "ID", label: "🇮🇩 Indonésie" },
  { value: "IQ", label: "🇮🇶 Irak" },
  { value: "IR", label: "🇮🇷 Iran" },
  { value: "IE", label: "🇮🇪 Irlande" },
  { value: "IS", label: "🇮🇸 Islande" },
  { value: "IL", label: "🇮🇱 Israël" },
  { value: "IT", label: "🇮🇹 Italie" },
  { value: "JM", label: "🇯🇲 Jamaïque" },
  { value: "JP", label: "🇯🇵 Japon" },
  { value: "JO", label: "🇯🇴 Jordanie" },
  { value: "KZ", label: "🇰🇿 Kazakhstan" },
  { value: "KE", label: "🇰🇪 Kenya" },
  { value: "KG", label: "🇰🇬 Kirghizistan" },
  { value: "KI", label: "🇰🇮 Kiribati" },
  { value: "KW", label: "🇰🇼 Koweït" },
  { value: "LA", label: "🇱🇦 Laos" },
  { value: "LS", label: "🇱🇸 Lesotho" },
  { value: "LV", label: "🇱🇻 Lettonie" },
  { value: "LB", label: "🇱🇧 Liban" },
  { value: "LY", label: "🇱🇾 Libye" },
  { value: "LI", label: "🇱🇮 Liechtenstein" },
  { value: "LT", label: "🇱🇹 Lituanie" },
  { value: "LU", label: "🇱🇺 Luxembourg" },
  { value: "MK", label: "🇲🇰 Macédoine du Nord" },
  { value: "MG", label: "🇲🇬 Madagascar" },
  { value: "MY", label: "🇲🇾 Malaisie" },
  { value: "MW", label: "🇲🇼 Malawi" },
  { value: "MV", label: "🇲🇻 Maldives" },
  { value: "MT", label: "🇲🇹 Malte" },
  { value: "MA", label: "🇲🇦 Maroc" },
  { value: "MH", label: "🇲🇭 Marshall" },
  { value: "MU", label: "🇲🇺 Maurice" },
  { value: "MX", label: "🇲🇽 Mexique" },
  { value: "FM", label: "🇫🇲 Micronésie" },
  { value: "MD", label: "🇲🇩 Moldavie" },
  { value: "MC", label: "🇲🇨 Monaco" },
  { value: "MN", label: "🇲🇳 Mongolie" },
  { value: "ME", label: "🇲🇪 Monténégro" },
  { value: "MZ", label: "🇲🇿 Mozambique" },
  { value: "MM", label: "🇲🇲 Myanmar" },
  { value: "NA", label: "🇳🇦 Namibie" },
  { value: "NR", label: "🇳🇷 Nauru" },
  { value: "NP", label: "🇳🇵 Népal" },
  { value: "NI", label: "🇳🇮 Nicaragua" },
  { value: "NO", label: "🇳🇴 Norvège" },
  { value: "NZ", label: "🇳🇿 Nouvelle-Zélande" },
  { value: "OM", label: "🇴🇲 Oman" },
  { value: "UG", label: "🇺🇬 Ouganda" },
  { value: "UZ", label: "🇺🇿 Ouzbékistan" },
  { value: "PK", label: "🇵🇰 Pakistan" },
  { value: "PW", label: "🇵🇼 Palaos" },
  { value: "PA", label: "🇵🇦 Panama" },
  { value: "PG", label: "🇵🇬 Papouasie-Nouvelle-Guinée" },
  { value: "PY", label: "🇵🇾 Paraguay" },
  { value: "NL", label: "🇳🇱 Pays-Bas" },
  { value: "PE", label: "🇵🇪 Pérou" },
  { value: "PH", label: "🇵🇭 Philippines" },
  { value: "PL", label: "🇵🇱 Pologne" },
  { value: "PT", label: "🇵🇹 Portugal" },
  { value: "QA", label: "🇶🇦 Qatar" },
  { value: "DO", label: "🇩🇴 République dominicaine" },
  { value: "CZ", label: "🇨🇿 République tchèque" },
  { value: "RO", label: "🇷🇴 Roumanie" },
  { value: "GB", label: "🇬🇧 Royaume-Uni" },
  { value: "RU", label: "🇷🇺 Russie" },
  { value: "RW", label: "🇷🇼 Rwanda" },
  { value: "KN", label: "🇰🇳 Saint-Kitts-et-Nevis" },
  { value: "LC", label: "🇱🇨 Sainte-Lucie" },
  { value: "SM", label: "🇸🇲 Saint-Marin" },
  { value: "VC", label: "🇻🇨 Saint-Vincent-et-les-Grenadines" },
  { value: "SB", label: "🇸🇧 Salomon" },
  { value: "WS", label: "🇼🇸 Samoa" },
  { value: "ST", label: "🇸🇹 São Tomé-et-Príncipe" },
  { value: "RS", label: "🇷🇸 Serbie" },
  { value: "SC", label: "🇸🇨 Seychelles" },
  { value: "SG", label: "🇸🇬 Singapour" },
  { value: "SK", label: "🇸🇰 Slovaquie" },
  { value: "SI", label: "🇸🇮 Slovénie" },
  { value: "SO", label: "🇸🇴 Somalie" },
  { value: "SD", label: "🇸🇩 Soudan" },
  { value: "SS", label: "🇸🇸 Soudan du Sud" },
  { value: "LK", label: "🇱🇰 Sri Lanka" },
  { value: "SE", label: "🇸🇪 Suède" },
  { value: "CH", label: "🇨🇭 Suisse" },
  { value: "SR", label: "🇸🇷 Suriname" },
  { value: "SY", label: "🇸🇾 Syrie" },
  { value: "TJ", label: "🇹🇯 Tadjikistan" },
  { value: "TZ", label: "🇹🇿 Tanzanie" },
  { value: "TD", label: "🇹🇩 Tchad" },
  { value: "TH", label: "🇹🇭 Thaïlande" },
  { value: "TL", label: "🇹🇱 Timor oriental" },
  { value: "TO", label: "🇹🇴 Tonga" },
  { value: "TT", label: "🇹🇹 Trinité-et-Tobago" },
  { value: "TN", label: "🇹🇳 Tunisie" },
  { value: "TM", label: "🇹🇲 Turkménistan" },
  { value: "TR", label: "🇹🇷 Turquie" },
  { value: "TV", label: "🇹🇻 Tuvalu" },
  { value: "UA", label: "🇺🇦 Ukraine" },
  { value: "UY", label: "🇺🇾 Uruguay" },
  { value: "VU", label: "🇻🇺 Vanuatu" },
  { value: "VA", label: "🇻🇦 Vatican" },
  { value: "VE", label: "🇻🇪 Venezuela" },
  { value: "VN", label: "🇻🇳 Viêt Nam" },
  { value: "YE", label: "🇾🇪 Yémen" },
  { value: "ZM", label: "🇿🇲 Zambie" },
  { value: "ZW", label: "🇿🇼 Zimbabwe" },
];

// Map code → label pour l'affichage dans le trigger
export const COUNTRY_MAP: Record<string, string> = Object.fromEntries(
  [...CEDEAO_COUNTRIES, ...OTHER_COUNTRIES].map((c) => [c.value, c.label]),
);
